### ISSUE TITLE
Excessive Memory Allocations and High Latency?

### ISSUE THREAD

**Issue by phillipCouto** [fzzy/radix#63] opened 2015-05-08 01:34 UTC
Hi Guys so I am starting to use redis in our environment for in memory database and caching but one thing that has held me back from fully adopting it for caching was the performance from using radix as the client and the increase in time to process requests. 

Now I know since we are communicating over the wire there is network latency but I am seeing 3-4 ms response times just to set a key in redis.
Also running a simple benchmark for set command here are my results:
```
BenchmarkSet	     300	   3952940 ns/op	    3794 B/op	      38 allocs/op
```

The redis instance is running on a boot2docker vm as a container on the same machine as the benchmarking code.

The code for the benchmark was:
```Go
func BenchmarkSet(b *testing.B) {
	c, err := redis.Dial("tcp", "127.0.0.1:32768")
	if err != nil {
		b.Fatal(err)
	}
	defer c.Close()

	for i := 0; i < b.N; i++ {
		resp := c.Cmd("SET", fmt.Sprintf("key%v", i), i)
		if resp.Err != nil {
			b.Fatal(resp.Err)
		}
	}
}
```

I know there are other libraries out there but I prefer the API of radix and would like to help if this issue is seen as legit amongst other users.

Am I alone on this issue?

**Comment by mediocregopher** [comment] 2015-05-08 03:34
Hey phillip, thanks for submitting such a detailed issue! Unfortunately I'm not able to reproduce your speed hangup, when I run your test I get the following output:

```
BenchmarkSet       50000             51007 ns/op            3745 B/op         33 allocs/op
```

Which seems more than reasonable to me. Could you try your test outside of docker? That's my best guess of where the latency could be coming from.

As a kind of control test, I came up with the following benchmark:

```go
func BenchmarkSetFaster(b *testing.B) {
    c, err := net.Dial("tcp", "127.0.0.1:6379")
    if err != nil {
        b.Fatal(err)
    }
    defer c.Close()
    bufr := bufio.NewReader(c)
    b.ResetTimer()

    for i := 0; i < b.N; i++ {
        fmt.Fprint(c, "*3\r\n$3\r\nSET\r\n$3\r\nfoo\r\n$3\r\nbar\r\n")
        bufr.ReadString('\n')
    }
}
```

...which is the fastest I could come up with for the test without dropping down into lower level network calls (which I didn't feel like bothering with). It got the following in the benchmark:

```
BenchmarkSetFaster        50000             39404 ns/op              32 B/op          3 allocs/op
```

Hopefuily this helps a bit. My guess is docker or your vm is screwing you over in some way.

**Comment by phillipCouto** [comment] 2015-05-08 11:31
I had the same feeling actually on my drive in and yeap it is the VM/Docker combination.

I am trying to figure out if it is the VM specifically or Docker that is causing the issue.

Just curious though doesn't 30+ allocations per command seem a little high?

**Comment by phillipCouto** [comment] 2015-05-08 12:11
Just for documentation purposes I ran the same benchmark in my production environment and
the results are:
```
BenchmarkSet        5000            264946 ns/op            3782 B/op         38 allocs/op
```
That is running redis-server in a container on one host and then running the benchmark in another container on a separate host.

Both hosts are located within the same rack on the same switch.

**Comment by mediocregopher** [comment] 2015-05-08 16:06
0.2ms seems fairly reasonable to me. If you're worried about that number though I'd give the benchmark I put up a shot, that should give you a good baseline on what latency is being caused by radix and what is just inherent in the system.

As for the memory allocations I don't really have any other numbers to compare against. I'll check out how some of the other redis drivers fair later today if I can.

**Comment by phillipCouto** [comment] 2015-05-08 16:10
Yeah 0.2 is definitely acceptable for me. I just wanted to post my findings so if someone else experiences a high latency issue they can see that its not all VM/docker setups that may lead to high latency.

I will run your Faster benchmark later and post it as well for reference.

**Comment by mediocregopher** [comment] 2015-05-08 16:33
That would be awesome. Here's your benchmark run against redigo:

```
BenchmarkSet      100000             16842 ns/op              88 B/op          7 allocs/op
```

So radix definitely has some room for improvement. I'll look into that in the next few days, I probably just need to be more mindful of heap allocations.

**Comment by phillipCouto** [comment] 2015-05-08 16:51
That is interesting how redigo is faster than your BenchmarkSetFaster which seems very raw to the naked eye.

**Comment by mediocregopher** [comment] 2015-05-08 17:18
Those benchmarks are actually on two different computers, when I redid BenchmarkSetFaster on this computer (the same one I did the redigo benchmark on) it was like 0.14 ms/op. Sorry, I should have posted that too

**Comment by phillipCouto** [comment] 2015-05-08 17:19
haha ok that makes sense now.

**Comment by mediocregopher** [comment] 2015-05-08 19:54
I've found the source of alot of the memory allocations in radix, I'll be working on that. Thanks for updating with your benchmarks! I'm gonna go ahead and close this out, re-open if you have any other problems. Good luck with your network latency problems :)

**Comment by phillipCouto** [comment] 2015-05-08 19:55
Thanks :)

**Closed by mediocregopher** 2015-05-08 19:54 UTC

**Comment by mediocregopher** [comment] 2015-05-09 22:30
As an update to this, I just pushed a set of changes with some fairly significant speed and memory allocation improvements. The benchmarks looks like this on my box now:

```
BenchmarkRadixOld     10000            113515 ns/op            3782 B/op         39 allocs/op
BenchmarkRadixNew     30000             56791 ns/op             427 B/op         19 allocs/op
BenchmarkRedigo       50000             28694 ns/op              88 B/op          7 allocs/op
BenchmarkRaw         100000             19320 ns/op              48 B/op          5 allocs/op
```

The numbers are still not _great_, but I've hit a bit of a limit with regards to the API. There's maybe one more optimization I could do but it would involve adding some strangeness to the API in order to keep it backwards compatible. Since one of the primary goals of radix is simplicity in the API I think it's not worth it.

If you're still interested I would recommend keeping an eye on [radix.v2](https://github.com/mediocregopher/radix.v2), where I'll be backporting these changes and hopefully making some further improvements to almost match redigo. Actually matching redigo will be very difficult, as radix provides for quite a bit more flexibility in what you can pass into it which in the end involves a bit of reflection.

**Comment by phillipCouto** [comment] 2015-05-09 22:34
That is a huge step!! Great work!

Of course I am interested like I said previously I picked radix for it's simplicity of API and how easy it was for me to wrap my head around it.
